server:
  url: "http://localhost"
  port: 80
  servlet:
    encoding:
      force-response: true
    session:
      cookie:
        secure: false

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: ${LOCAL_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: create
  session:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace