server:
  url: "https://api.ducks.site"
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://${PROD_DB_ENDPOINT}:3306/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


