server:
  url: "https://dev.ducks.site"
  port: 8081
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:mariadb://${DEV_DB_ENDPOINT}:3306/${DEV_DB_NAME}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
